package com.jvanier.android.sendtocar.models;

import java.util.Arrays;
import java.util.Locale;

public final class GoogleMapsHosts {
	// @formatter:off
	final public static String hosts[] = {
		"maps.google.com.br",
		"maps.google.fr",
		"maps.google.de",
		"maps.google.co.in",
		"maps.google.it",
		"maps.google.co.jp",
		"maps.google.ru",
		"maps.google.es",
		"maps.google.co.uk",
		"maps.google.co.uk",
		"maps.google.com",
		"maps.google.com.au",
		"maps.google.be",
		"maps.google.ca",
		"maps.google.nl",
		"maps.google.no",
		"maps.google.pl",
		"maps.google.ch",
		"maps.google.com.tw",
		"maps.google.dz",
		"maps.google.com.ar",
		"maps.google.at",
		"maps.google.cl",
		"ditu.google.cn",
		"ditu.google.com",
		"maps.google.cz",
		"maps.google.dk",
		"maps.google.com.eg",
		"maps.google.fi",
		"maps.google.gr",
		"maps.google.com.hk",
		"maps.google.hu",
		"maps.google.co.id",
		"maps.google.jo",
		"maps.google.co.ke",
		"maps.google.co.kr",
		"maps.google.com.my",
		"maps.google.com.mx",
		"maps.google.co.nz",
		"maps.google.pt",
		"maps.google.com.sa",
		"maps.google.com.sg",
		"maps.google.co.za",
		"maps.google.se",
		"maps.google.co.th",
		"maps.google.ae",
		"maps.google.co.ac",
		"maps.google.com.bh",
		"maps.google.bj",
		"maps.google.co.bw",
		"maps.google.bi",
		"maps.google.cf",
		"maps.google.td",
		"maps.google.cg",
		"maps.google.cd",
		"maps.google.ci",
		"maps.google.dj",
		"maps.google.ga",
		"maps.google.gm",
		"maps.google.com.gh",
		"maps.google.iq",
		"maps.google.com.kw",
		"maps.google.com.lb",
		"maps.google.com.ly",
		"maps.google.li",
		"maps.google.mw",
		"maps.google.mu",
		"maps.google.co.mz",
		"maps.google.com.na",
		"maps.google.com.ng",
		"maps.google.com.om",
		"maps.google.com.qa",
		"maps.google.rw",
		"maps.google.st",
		"maps.google.sc",
		"maps.google.com.sl",
		"maps.google.co.tz",
		"maps.google.tg",
		"maps.google.tn",
		"maps.google.co.ug",
		"maps.google.co.zm",
		"maps.google.co.zw",
		"maps.google.cn",

		// European countries that use the German car list
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
		"maps.google.de",
	};
	
	final public static String countries[] = {
		"br",
		"fr",
		"de",
		"in",
		"it",
		"jp",
		"ru",
		"es",
		"gb",
		"uk",
		"us",
		"au",
		"be",
		"ca",
		"nl",
		"no",
		"pl",
		"ch",
		"tw",
		"dz",
		"ar",
		"at",
		"cl",
		"cn",
		"cn",
		"cz",
		"dk",
		"eg",
		"fi",
		"gr",
		"hk",
		"hu",
		"id",
		"jo",
		"ke",
		"kr",
		"my",
		"mx",
		"nz",
		"pt",
		"sa",
		"sg",
		"za",
		"se",
		"th",
		"ae",
		"ac",
		"bh",
		"bj",
		"bw",
		"bi",
		"cf",
		"td",
		"cg",
		"cd",
		"ci",
		"dj",
		"ga",
		"gm",
		"gh",
		"iq",
		"kw",
		"lb",
		"ly",
		"li",
		"mw",
		"mu",
		"mz",
		"na",
		"ng",
		"om",
		"qa",
		"rw",
		"st",
		"sc",
		"sl",
		"tz",
		"tg",
		"tn",
		"ug",
		"zm",
		"zw",
		"cn",
		
		// European countries that use the German car list
		"al",
		"ad",
		"by",
		"ba",
		"bg",
		"hr",
		"cy",
		"ee",
		"fo",
		"gi",
		"is",
		"ie",
		"lv",
		"lt",
		"lu",
		"mk",
		"mt",
		"md",
		"mc",
		"ro",
		"sm",
		"rs",
		"sk",
		"si",
		"ua",
		"va",
		"me",
	};
	// @formatter:on

	public static String getHostByCountry(String country) {
		country = country.toLowerCase(Locale.US);
		for(int c = 0; c < countries.length; c++) {
			if(countries[c].equals(country)) {
				return hosts[c];
			}
		}
		return null;
	}

	public static boolean doesHostExist(String host) {
		return Arrays.asList(hosts).contains(host.toLowerCase(Locale.US));
	}
}